{{- $statsConfig := coalesce .Values.discovery.deployment.stats .Values.global.glooStats -}}
{{- if and $statsConfig.enabled $statsConfig.serviceMonitorEnabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    discovery.solo.io/function_discovery: disabled
    app: gloo
    gloo: discovery
  name: discovery
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http-monitoring
      port: 9091
  selector:
    gloo: discovery
{{- end -}}